# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\TDLTC4\LearnPyQtDesign\S5LearnQMainWindow\MyMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 619)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(150, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(150, 170, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditName.setFont(font)
        self.lineEditName.setObjectName("lineEditName")
        self.pushButtonSendName = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSendName.setGeometry(QtCore.QRect(150, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonSendName.setFont(font)
        self.pushButtonSendName.setObjectName("pushButtonSendName")
        self.pushButtonVisitBlog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonVisitBlog.setGeometry(QtCore.QRect(300, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonVisitBlog.setFont(font)
        self.pushButtonVisitBlog.setObjectName("pushButtonVisitBlog")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(460, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "Your Name:"))
        self.lineEditName.setText(_translate("MainWindow", "Lâm Thùy Dung"))
        self.pushButtonSendName.setText(_translate("MainWindow", "Send Name"))
        self.pushButtonVisitBlog.setText(_translate("MainWindow", "Visit Blog"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
