# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\TDLT\Module7\C127DoiFThanhC\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 338)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelF = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelF.setGeometry(QtCore.QRect(50, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelF.setFont(font)
        self.labelF.setObjectName("labelF")
        self.lineEditF = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditF.setGeometry(QtCore.QRect(210, 40, 241, 41))
        self.lineEditF.setObjectName("lineEditF")
        self.pushButtonConvert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConvert.setGeometry(QtCore.QRect(270, 110, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonConvert.setFont(font)
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        self.labelC = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelC.setGeometry(QtCore.QRect(50, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelC.setFont(font)
        self.labelC.setObjectName("labelC")
        self.labelCrs = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCrs.setGeometry(QtCore.QRect(210, 180, 231, 41))
        self.labelCrs.setText("")
        self.labelCrs.setObjectName("labelCrs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelF.setText(_translate("MainWindow", "Fahrenheit (F):"))
        self.pushButtonConvert.setText(_translate("MainWindow", "Convert"))
        self.labelC.setText(_translate("MainWindow", "Celsius (C):"))
