# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\TDLT\Module7\C135Ptb1\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 360)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(60, 30, 331, 81))
        font = QtGui.QFont()
        font.setFamily("SVN-HC East Market")
        font.setPointSize(24)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 110, 301, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.hSALabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.hSALabel.setObjectName("hSALabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.hSALabel)
        self.hSALineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.hSALineEdit.setObjectName("hSALineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.hSALineEdit)
        self.hSBLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.hSBLabel.setObjectName("hSBLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.hSBLabel)
        self.hSBLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.hSBLineEdit.setObjectName("hSBLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.hSBLineEdit)
        self.labelKqua = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelKqua.setGeometry(QtCore.QRect(80, 210, 52, 15))
        self.labelKqua.setObjectName("labelKqua")
        self.lineEditKqua = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditKqua.setGeometry(QtCore.QRect(140, 210, 241, 21))
        self.lineEditKqua.setObjectName("lineEditKqua")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 170, 171, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonGiai = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonGiai.setObjectName("pushButtonGiai")
        self.horizontalLayout.addWidget(self.pushButtonGiai)
        self.pushButtonTiep = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonTiep.setObjectName("pushButtonTiep")
        self.horizontalLayout.addWidget(self.pushButtonTiep)
        self.pushButtonThoat = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonThoat.setObjectName("pushButtonThoat")
        self.horizontalLayout.addWidget(self.pushButtonThoat)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff007f;\">Phương trình bậc 1</span></p></body></html>"))
        self.hSALabel.setText(_translate("MainWindow", "Hệ số a:"))
        self.hSBLabel.setText(_translate("MainWindow", "Hệ số b:"))
        self.labelKqua.setText(_translate("MainWindow", "Kết quả:"))
        self.pushButtonGiai.setText(_translate("MainWindow", "Giải"))
        self.pushButtonTiep.setText(_translate("MainWindow", "Tiếp"))
        self.pushButtonThoat.setText(_translate("MainWindow", "Thoát"))
