# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\TDLT\LearnPyQtDesign\S14LearnQCheckBoxBasicWidgets\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(190, 90, 371, 61))
        self.labelTitle.setObjectName("labelTitle")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(200, 160, 351, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.fullNameLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.fullNameLabel.setObjectName("fullNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fullNameLabel)
        self.fullNameLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.fullNameLineEdit.setObjectName("fullNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fullNameLineEdit)
        self.emailLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emailLabel)
        self.emailLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailLineEdit)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 220, 241, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEditCoursesSelection = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget)
        self.textEditCoursesSelection.setObjectName("textEditCoursesSelection")
        self.verticalLayout.addWidget(self.textEditCoursesSelection)
        self.checkBoxMachineLearning = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBoxMachineLearning.setObjectName("checkBoxMachineLearning")
        self.verticalLayout.addWidget(self.checkBoxMachineLearning)
        self.checkBoxDeepLeaning = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBoxDeepLeaning.setObjectName("checkBoxDeepLeaning")
        self.verticalLayout.addWidget(self.checkBoxDeepLeaning)
        self.checkBoxSmartContract = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBoxSmartContract.setObjectName("checkBoxSmartContract")
        self.verticalLayout.addWidget(self.checkBoxSmartContract)
        self.pushButtonSubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(350, 350, 91, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Dung Lam\\PycharmProjects\\TDLT\\LearnPyQtDesign\\S14LearnQCheckBoxBasicWidgets\\images/IconSubmit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSubmit.setIcon(icon)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-style:italic; color:#0000ff;\">Courses Registration</span></p></body></html>"))
        self.fullNameLabel.setText(_translate("MainWindow", "Full Name"))
        self.emailLabel.setText(_translate("MainWindow", "Email:"))
        self.textEditCoursesSelection.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\" bgcolor=\"#ffff00\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Courses Selection</span></p></body></html>"))
        self.checkBoxMachineLearning.setText(_translate("MainWindow", "Machine Learning"))
        self.checkBoxDeepLeaning.setText(_translate("MainWindow", "Deep Learning"))
        self.checkBoxSmartContract.setText(_translate("MainWindow", "Smart Contract"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Submit"))
