# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\KTLT\Module1\C24PhanMemLuckyNumber\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 462)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 431, 331))
        self.groupBox.setObjectName("groupBox")
        self.labelSo1 = QtWidgets.QLabel(parent=self.groupBox)
        self.labelSo1.setGeometry(QtCore.QRect(70, 40, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.labelSo1.setFont(font)
        self.labelSo1.setStyleSheet("background: rgb(221, 255, 255);\n"
"color: rgb(255, 0, 127);")
        self.labelSo1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSo1.setObjectName("labelSo1")
        self.labelSo2 = QtWidgets.QLabel(parent=self.groupBox)
        self.labelSo2.setGeometry(QtCore.QRect(170, 40, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.labelSo2.setFont(font)
        self.labelSo2.setStyleSheet("background: rgb(221, 255, 255);\n"
"color: rgb(255, 0, 127);")
        self.labelSo2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSo2.setObjectName("labelSo2")
        self.labelSo3 = QtWidgets.QLabel(parent=self.groupBox)
        self.labelSo3.setGeometry(QtCore.QRect(270, 40, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.labelSo3.setFont(font)
        self.labelSo3.setStyleSheet("background: rgb(221, 255, 255);\n"
"color: rgb(255, 0, 127);")
        self.labelSo3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSo3.setObjectName("labelSo3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(90, 180, 71, 21))
        self.label_4.setObjectName("label_4")
        self.lineEditTienMay = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTienMay.setEnabled(False)
        self.lineEditTienMay.setGeometry(QtCore.QRect(160, 180, 151, 20))
        self.lineEditTienMay.setObjectName("lineEditTienMay")
        self.lineEditTienNguoi = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTienNguoi.setEnabled(False)
        self.lineEditTienNguoi.setGeometry(QtCore.QRect(160, 210, 151, 20))
        self.lineEditTienNguoi.setObjectName("lineEditTienNguoi")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(90, 210, 71, 21))
        self.label_5.setObjectName("label_5")
        self.pushButtonQuaySo = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonQuaySo.setGeometry(QtCore.QRect(60, 260, 81, 41))
        self.pushButtonQuaySo.setObjectName("pushButtonQuaySo")
        self.pushButtonGameMoi = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonGameMoi.setGeometry(QtCore.QRect(170, 260, 81, 41))
        self.pushButtonGameMoi.setObjectName("pushButtonGameMoi")
        self.pushButtonKetThuc = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonKetThuc.setGeometry(QtCore.QRect(280, 260, 81, 41))
        self.pushButtonKetThuc.setObjectName("pushButtonKetThuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Game quay số:"))
        self.labelSo1.setText(_translate("MainWindow", "7"))
        self.labelSo2.setText(_translate("MainWindow", "7"))
        self.labelSo3.setText(_translate("MainWindow", "7"))
        self.label_4.setText(_translate("MainWindow", "Tiền máy: "))
        self.lineEditTienMay.setText(_translate("MainWindow", "100"))
        self.lineEditTienNguoi.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "Tiền người:"))
        self.pushButtonQuaySo.setText(_translate("MainWindow", "Quay số"))
        self.pushButtonGameMoi.setText(_translate("MainWindow", "Game mới"))
        self.pushButtonKetThuc.setText(_translate("MainWindow", "Kết thúc"))
