# Form implementation generated from reading ui file 'C:\Users\Dung Lam\PycharmProjects\TDLT\Module7\C128ChuyenDuongLichThanhAmLich\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 334)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelDuong = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelDuong.setGeometry(QtCore.QRect(70, 50, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelDuong.setFont(font)
        self.labelDuong.setObjectName("labelDuong")
        self.lineEditDuong = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDuong.setGeometry(QtCore.QRect(320, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditDuong.setFont(font)
        self.lineEditDuong.setObjectName("lineEditDuong")
        self.pushButtonChuyen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonChuyen.setGeometry(QtCore.QRect(340, 120, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonChuyen.setFont(font)
        self.pushButtonChuyen.setObjectName("pushButtonChuyen")
        self.labelAm = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAm.setGeometry(QtCore.QRect(70, 180, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAm.setFont(font)
        self.labelAm.setObjectName("labelAm")
        self.labelResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(320, 190, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelDuong.setText(_translate("MainWindow", "Nhập năm Dương lịch:"))
        self.pushButtonChuyen.setText(_translate("MainWindow", "Chuyển"))
        self.labelAm.setText(_translate("MainWindow", "Nhập năm Âm lịch:"))
